### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by bradfordcondon**
Hi Lacey!

OK we've got two test files, the one you gave me and the one i generated.  Mine fails, your passes.  It's a good start.

We have 

* Travis-CI
* A unit test that checks if the bibtex file gets loaded into chado
* Some small things to get it working in 7.x-3.x, namely loading the API file (i feel like tripal_chado should relocate the methods we use into the actual api folder so we dont need to do this)

### CODE REVIEW

**Comment by bradfordcondon** [comment]
Tests will fail until my file loads and/or we comment out that other test, by the way.

**Comment by laceysanderson** [comment]
Awesome! THANK YOU <3

I don't want to merge it with tests failing tho... Perhaps we comment out the failing test at this point since it's testing functionality that's not supported? Then we can add it back in once I fix that :-)

**Comment by bradfordcondon** [comment]
Yeah I can get behind that.

**Comment by bradfordcondon** [comment]
passing now :)

**Review by laceysanderson — APPROVED** [review]

**Comment by laceysanderson** [comment]
Yay!

**Pull request merged**
